# Generated by Django 4.1.5 on 2023-05-27 22:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_follow_id_alter_post_id_alter_reply_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='views', to=settings.AUTH_USER_MODEL),
        ),
    ]
